# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=True)),
            ],
        ),
    ]
