# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20180624_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='count',
        ),
        migrations.AddField(
            model_name='url',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
